### PR TITLE
my fix for my issue representing my user story

### PR DESCRIPTION
**Pull request by MichaelHilton**
It works!

### CODE REVIEW

**Comment by nelsonni** [comment]
This PR does not result in runnable code. The Battleship class is not fully complete. Needs further development.

**Comment by MichaelHilton** [comment]
@nelsonni I need more details...

**Comment by nelsonni** [comment]
Battleship is an empty Java class.

**Comment by nelsonni** [comment]
@MichaelHilton Looks good.

**Comment by nelsonni** [comment]
Done.

**Pull request merged**
